<a href="https://colab.research.google.com/github/sumantChoix/ChoixOrderManageMent/blob/main/Python_for_tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np 
from tensorflow import keras

2.12.0


In [ ]:
xs = np.array([1.0,1.1,1.2,1.3,1.4] , dtype=float);
ys=np.array([2.0,2.2,2.4,2.6,2.8] , dtype=float);
print(xs)
model = tf.keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])]);

model.compile(optimizer='sgd',loss='mean_squared_error');
model.fit(xs ,ys,epochs=500)


[1.  1.1 1.2 1.3 1.4]
Epoch 1/500
1/1 [==============================] - 0s 312ms/step - loss: 0.7142
Epoch 2/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6460
Epoch 3/500
1/1 [==============================] - 0s 11ms/step - loss: 0.5844
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 0.5286
Epoch 5/500
1/1 [==============================] - 0s 9ms/step - loss: 0.4782
Epoch 6/500
1/1 [==============================] - 0s 11ms/step - loss: 0.4326
Epoch 7/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3914
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3541
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3204
Epoch 10/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2899
Epoch 11/500
1/1 [==============================] - 0s 8ms/step - loss: 0.2623
Epoch 12/500
1/1 [==============================] - 0s 9ms/step - loss: 0.2374
Epoch 13/500
1/1 [==============

In [ ]:
print(model.predict([1.5]))



1/1 [==============================] - 0s 75ms/step
[[2.9240909]]


In [ ]:
import tensorflow as tf
 
## print(tf.constant([4,5]))

## print(tf.ones(shape=(2,2)))

## print(tf.zeros(shape=(3,3)))

## print(tf.random.uniform(shape=(2, 3), minval=0, maxval=1))
x=tf.constant([4,5])
y=tf.constant([5,5])


## MATHMATICAL OPERATION IN TENSORFLOW 

print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.divide(x,y))


tf.Tensor([ 9 10], shape=(2,), dtype=int32)
tf.Tensor([-1  0], shape=(2,), dtype=int32)
tf.Tensor([0.8 1. ], shape=(2,), dtype=float64)


In [ ]:
import tensorflow as tf 
from tensorflow import keras
from  tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

a=tf.Variable(([12,45,25,78],[45,85,78,25]))

print(a.numpy())

AttributeError: ignored

In [ ]:
import tensorflow as tf
a=tf.constant(([12,5,15],
              [45,85,65],[5,8,10]
              ));
tf.random.set_seed(42)
b=tf.random.shuffle(a,seed=2)
b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12,  5, 15],
       [45, 85, 65],
       [ 5,  8, 10]], dtype=int32)>

In [ ]:
import numpy as np
import tensorflow as  tf 
a = tf.zeros(shape=[6,2,3],dtype='int8')
tf.size(a).numpy()

36